# Generated by Django 5.0.4 on 2024-10-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='residence',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
