# Generated by Django 5.0.4 on 2024-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='project',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
