# Generated by Django 5.0.4 on 2024-11-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactus_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contacts'},
        ),
    ]
